config/routes.rb
Rails.application.routes.draw do
  scope :api do
    get "works/chart"

    resources :depts
    resources :ranks
    resources :groups
    resources :systems
    resources :months
    resources :projects
    resources :users
    resources :orders
    resources :works
    resources :costs
    resources :assigns

    namespace :assigns do
      resources :users, only: [:show, :edit, :update]
    end
  end

  root "project#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assign.rb
class Assign < ApplicationRecord
  belongs_to :order, required: true
  belongs_to :user, required: true
  belongs_to :month, required: true

  scope :aligned, -> {
    all.sort_by do |assign|
      [
        assign.order.sortkey,
        assign.user.rank.id,
        assign.user.number,
        assign.month.date
      ]
    end
  }

end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :order, required: true
  belongs_to :rank, required: true
  belongs_to :month, required: true
end

app/models/dept.rb
class Dept < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :dept, required: true
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/month.rb
class Month < ApplicationRecord
  validates :date, presence: true, uniqueness: true

  has_many :works
  has_many :costs
  has_many :assigns
  has_many :orders, through: :assigns

  validate :must_be_first_day_of_month

  def must_be_first_day_of_month
    if date.day != 1
      errors.add(:illegal_date, "日付は月初１日でなくてはならない")
    end
  end

  def name
    date.strftime("%Y-%m")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :project, required: true
  belongs_to :group, required: true
  belongs_to :system, required: true

  has_many :assigns

  scope :aligned, -> { includes(:project, :group, :system).order("projects.number, groups.id, systems.number") }

  def name
    [project.number, project.name, group.name, system.number, system.name].join(' ')
  end

  def sortkey
    sprintf("%12s%02d%10s", project.number, group.id, system.number)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :orders

  def fullname
    "#{number}:#{name}"
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :unit_price, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  belongs_to :month
  belongs_to :step
end

app/models/step.rb
class Step < ApplicationRecord
end

app/models/system.rb
class System < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :rank, required: true
  belongs_to :group, required: true

  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :works
  has_many :assigns
  has_many :orders, through: :assigns
  has_many :projects, through: :orders

  accepts_nested_attributes_for :assigns, allow_destroy: true

  scope :aligned, -> { includes(:group, :rank).order("ranks.number desc").order(number: :asc) }

  def fullname
    number + " " + name
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :month, required: true

  validates :user, uniqueness: { scope: :month }
  validates :power, presence: true
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :months
  has_many :assigns, through: :months
  has_many :orders, through: :assigns
  has_many :users, through: :assigns
end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cost_params
      params.require(:cost).permit(:oeder_id, :rank_id, :month, :power)
    end
end

app/controllers/orders/costs_controller.rb
class Orders::CostsController < CostsController
  before_action :set_order

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.where(order: @order).aligned
    @months = Month.all
  end

  # GET /Costs/new
  def new
    @cost = Cost.new
  end

  private
    def set_order
      @order = Order.find(params[:order_id])
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/costs/_form.html.slim
= simple_form_for @cost, :html => { :class => "form-horizontal" } do |f|
  = f.association :order
  = f.association :rank
  = f.association :month
  = f.input :power
  = f.button :submit, :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), costs_path, :class => 'btn btn-default'

app/views/costs/edit.html.slim
- model_class = Cost
.page-header
  h2=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/costs/index.html.slim
- model_class = Cost
.page-header
  h2=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:order_id)
      th= model_class.human_attribute_name(:rank_id)
      th= model_class.human_attribute_name(:month)
      th= model_class.human_attribute_name(:power)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @costs.each do |cost|
      tr
        td= link_to cost.id, cost_path(cost)
        td= cost.order&.name
        td= cost.rank&.name
        td= cost.month&.name
        td= cost.power
        td
          = link_to t('.show', :default => t("helpers.links.show")), cost_path(cost), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_cost_path(cost), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), cost_path(cost), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_cost_path, :class => 'btn btn-primary'

app/views/costs/new.html.slim
- model_class = Cost
.page-header
  h2=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/costs/show.html.slim
- model_class = Cost
.page-header
  h2=t '.title', :default => model_class.model_name.human.titleize

p
  strong= model_class.human_attribute_name(:order_id) + ':'
  br
  = @cost.order&.name
p
  strong= model_class.human_attribute_name(:rank_id) + ':'
  br
  = @cost.rank&.name
p
  strong= model_class.human_attribute_name(:month) + ':'
  br
  = @cost.month
p
  strong= model_class.human_attribute_name(:power) + ':'
  br
  = @cost.power

= link_to t('.back', :default => t("helpers.links.back")), costs_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_cost_path(@cost), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), cost_path(@cost), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'