config/routes.rb
Rails.application.routes.draw do
  scope :api do
    get "works/chart"

    resources :depts
    resources :ranks
    resources :groups
    resources :systems
    resources :months
    resources :projects
    resources :users
    resources :orders
    resources :works
    resources :costs
    resources :assigns

    namespace :assigns do
      resources :users, only: [:show, :edit, :update]
    end
  end

  root "project#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assign.rb
class Assign < ApplicationRecord
  belongs_to :order, required: true
  belongs_to :user, required: true
  belongs_to :month, required: true

  scope :aligned, -> {
    all.sort_by do |assign|
      [
        assign.order.sortkey,
        assign.user.rank.id,
        assign.user.number,
        assign.month.date
      ]
    end
  }

end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :order, required: true
  belongs_to :rank, required: true
  belongs_to :month, required: true
end

app/models/dept.rb
class Dept < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :dept, required: true
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/month.rb
class Month < ApplicationRecord
  validates :date, presence: true, uniqueness: true

  has_many :works
  has_many :costs
  has_many :assigns
  has_many :orders, through: :assigns

  validate :must_be_first_day_of_month

  def must_be_first_day_of_month
    if date.day != 1
      errors.add(:illegal_date, "日付は月初１日でなくてはならない")
    end
  end

  def name
    date.strftime("%Y-%m")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :project, required: true
  belongs_to :group, required: true
  belongs_to :system, required: true

  has_many :assigns

  scope :aligned, -> { includes(:project, :group, :system).order("projects.number, groups.id, systems.number") }

  def name
    [project.number, project.name, group.name, system.number, system.name].join(' ')
  end

  def sortkey
    sprintf("%12s%02d%10s", project.number, group.id, system.number)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :orders

  def fullname
    "#{number}:#{name}"
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :unit_price, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  belongs_to :month
  belongs_to :step
end

app/models/step.rb
class Step < ApplicationRecord
end

app/models/system.rb
class System < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :rank, required: true
  belongs_to :group, required: true

  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :works
  has_many :assigns
  has_many :orders, through: :assigns
  has_many :projects, through: :orders

  accepts_nested_attributes_for :assigns, allow_destroy: true

  scope :aligned, -> { includes(:group, :rank).order("ranks.number desc").order(number: :asc) }

  def fullname
    number + " " + name
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :month, required: true

  validates :user, uniqueness: { scope: :month }
  validates :power, presence: true
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :months
  has_many :assigns, through: :months
  has_many :orders, through: :assigns
  has_many :users, through: :assigns
end

app/controllers/assigns/users_controller.rb
class Assigns::UsersController < UsersController
  before_action :set_year

  # GET /assigns
  # GET /assigns.json
  def show
    respond_to do |format|
      format.html

      format.json do
        @assigns = @year
          .assigns
          .includes(:order)
          .where(user_id: @user.id)
          .distinct

        @orders = @year
          .orders
          .includes(:project, :group, :system)
          .where(assigns: { user_id: @user.id })
          .distinct

        @months = @year.months

        @users = User.aligned
        @all_orders = Order.aligned

        @assign_table = {}
        @assigns.each do |assign|
          @assign_table[assign.order_id] ||= {}
          @assign_table[assign.order_id][assign.month_id] = assign
        end
      end
    end
  end

  private
    def set_year
      if year_id = params[:year_id]
        @year = Year.find(year_id)
      else
        @year = Year.find_by(date: Date.today.beginning_of_year)
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(assigns_attributes: [:id, :order_id, :user_id, :month_id, :power, :_destroy])
    end

end

app/controllers/assigns_controller.rb
class AssignsController < ApplicationController
  before_action :set_assign, only: [:show, :edit, :update, :destroy]

  # GET /assigns
  # GET /assigns.json
  def index
    @assigns = Assign.all.sort_by{ |a| [a.order.sortkey, a.user.number, a.month.date] }
  end

  # GET /assigns/1
  # GET /assigns/1.json
  def show
  end

  # GET /assigns/new
  def new
    @assign = Assign.new
  end

  # GET /assigns/1/edit
  def edit
  end

  # POST /assigns
  # POST /assigns.json
  def create
    @assign = Assign.new(assign_params)

    respond_to do |format|
      if @assign.save
        format.html { redirect_to @assign, notice: 'Assign was successfully created.' }
        format.json { render :show, status: :created, location: @assign }
      else
        format.html { render :new }
        format.json { render json: @assign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assigns/1
  # PATCH/PUT /assigns/1.json
  def update
    respond_to do |format|
      if @assign.update(assign_params)
        format.html { redirect_to @assign, notice: 'Assign was successfully updated.' }
        format.json { render :show, status: :ok, location: @assign }
      else
        format.html { render :edit }
        format.json { render json: @assign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assigns/1
  # DELETE /assigns/1.json
  def destroy
    @assign.destroy
    respond_to do |format|
      format.html { redirect_to assigns_url, notice: 'Assign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assign
      @assign = Assign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assign_params
      params.require(:assign).permit(:order_id, :user_id, :month_id, :power)
    end
end

app/controllers/orders/assigns_controller.rb
class Orders::AssignsController < AssignsController
  before_action :set_order

  # GET /assigns
  # GET /assigns.json
  def index
    @assigns = Assign.where(order: @order)
    @months = Month.all
  end

  # GET /assigns/new
  def new
    @assign = Assign.new
  end

  private
    def set_order
      @order = Order.find(params[:order_id])
    end
end

app/helpers/assigns_helper.rb
module AssignsHelper
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/months_helper.rb
module MonthsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/assigns/_form.html.slim
= simple_form_for @assign, :html => { :class => "form-horizontal" } do |f|
  = f.association :order
  = f.association :user
  = f.association :month
  = f.input :power
  = f.button :submit, :class => 'btn-primary'
  '
  = link_to t('.cancel', :default => t("helpers.links.cancel")), assigns_path, :class => 'btn btn-default'

app/views/assigns/edit.html.slim
- model_class = Assign
.page-header
  h2=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/assigns/index.html.slim
- model_class = Assign
.page-header
  h2=t '.title', :default => model_class.model_name.human.pluralize.titleize
table.table.table-striped
  thead
    tr
      th= model_class.human_attribute_name(:id)
      th= model_class.human_attribute_name(:order_id)
      th= model_class.human_attribute_name(:user_id)
      th= model_class.human_attribute_name(:month_id)
      th= model_class.human_attribute_name(:power)
      th=t '.actions', :default => t("helpers.actions")
  tbody
    - @assigns.each do |assign|
      tr
        td= link_to assign.id, assign_path(assign)
        td= assign.order&.name
        td= assign.user&.name
        td= assign.month&.name
        td= assign.power
        td
          = link_to t('.show', :default => t("helpers.links.show")), assign_path(assign), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_assign_path(assign), :class => 'btn btn-default btn-xs'
          '
          = link_to t('.destroy', :default => t("helpers.links.destroy")), assign_path(assign), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_assign_path, :class => 'btn btn-primary'

app/views/assigns/new.html.slim
- model_class = Assign
.page-header
  h2=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/assigns/show.html.slim
- model_class = Assign
.page-header
  h2=t '.title', :default => model_class.model_name.human.titleize
p
  strong= model_class.human_attribute_name(:order_id) + ':'
  br
  = @assign.order&.name
p
  strong= model_class.human_attribute_name(:user_id) + ':'
  br
  = @assign.user&.name
p
  strong= model_class.human_attribute_name(:month) + ':'
  br
  = @assign.month&.name
p
  strong= model_class.human_attribute_name(:power) + ':'
  br
  = @assign.power

= link_to t('.back', :default => t("helpers.links.back")), assigns_path, :class => 'btn btn-default'
'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_assign_path(@assign), :class => 'btn btn-default'
'
= link_to t('.destroy', :default => t("helpers.links.destroy")), assign_path(@assign), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'