config/routes.rb
Rails.application.routes.draw do
  scope :api do
    get "works/chart"

    resources :depts
    resources :ranks
    resources :groups
    resources :systems
    resources :months
    resources :projects
    resources :users
    resources :orders
    resources :works
    resources :costs
    resources :assigns

    namespace :assigns do
      resources :users, only: [:show, :edit, :update]
    end
  end

  root "project#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assign.rb
class Assign < ApplicationRecord
  belongs_to :order, required: true
  belongs_to :user, required: true
  belongs_to :month, required: true

  scope :aligned, -> {
    all.sort_by do |assign|
      [
        assign.order.sortkey,
        assign.user.rank.id,
        assign.user.number,
        assign.month.date
      ]
    end
  }

end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :order, required: true
  belongs_to :rank, required: true
  belongs_to :month, required: true
end

app/models/dept.rb
class Dept < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :dept, required: true
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/month.rb
class Month < ApplicationRecord
  validates :date, presence: true, uniqueness: true

  has_many :works
  has_many :costs
  has_many :assigns
  has_many :orders, through: :assigns

  validate :must_be_first_day_of_month

  def must_be_first_day_of_month
    if date.day != 1
      errors.add(:illegal_date, "日付は月初１日でなくてはならない")
    end
  end

  def name
    date.strftime("%Y-%m")
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :project, required: true
  belongs_to :group, required: true
  belongs_to :system, required: true

  has_many :assigns

  scope :aligned, -> { includes(:project, :group, :system).order("projects.number, groups.id, systems.number") }

  def name
    [project.number, project.name, group.name, system.number, system.name].join(' ')
  end

  def sortkey
    sprintf("%12s%02d%10s", project.number, group.id, system.number)
  end
end

app/models/project.rb
class Project < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :orders

  def fullname
    "#{number}:#{name}"
  end
end

app/models/rank.rb
class Rank < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
  validates :unit_price, presence: true
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  belongs_to :month
  belongs_to :step
end

app/models/step.rb
class Step < ApplicationRecord
end

app/models/system.rb
class System < ApplicationRecord
  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :rank, required: true
  belongs_to :group, required: true

  validates :number, presence: true, uniqueness: true
  validates :name, presence: true, uniqueness: true

  has_many :works
  has_many :assigns
  has_many :orders, through: :assigns
  has_many :projects, through: :orders

  accepts_nested_attributes_for :assigns, allow_destroy: true

  scope :aligned, -> { includes(:group, :rank).order("ranks.number desc").order(number: :asc) }

  def fullname
    number + " " + name
  end
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user, required: false
  belongs_to :month, required: true

  validates :user, uniqueness: { scope: :month }
  validates :power, presence: true
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :months
  has_many :assigns, through: :months
  has_many :orders, through: :assigns
  has_many :users, through: :assigns
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/depts_helper.rb
module DeptsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Workplan"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"

  body
    = nav_bar fixed: :top, brand: "WorkPlan" do
      = menu_group
        = drop_down "マスター管理"
          = menu_item '部', depts_path
          = menu_item 'ランク', ranks_path
          = menu_item 'グループ', groups_path
          = menu_item '担当者', users_path
          = menu_item 'システム', systems_path
          = menu_item 'プロジェクト', projects_path
          = menu_item '発注情報', orders_path
          
        = drop_down "月別入力"
          = menu_item '要員計画', '/#/works/'
          = menu_item '開発計画', '/#/costs/'
          = menu_item 'アサイン', '/#/assigns/'

        = drop_down "データ補正"
          = menu_item '要員計画', works_path
          = menu_item '発注情報', orders_path
          = menu_item '開発計画', costs_path
          = menu_item 'アサイン', assigns_path

    .container#app
      = bootstrap_flash
      = yield